### ISSUE TITLE
[Question] About anti-virus safety of this flatpak

### ISSUE THREAD

**Issue by Nokia808** [flathub/com.usebottles.bottles#1]
Hello !

1st of all, I would like to thank you a lot for shipping this application as flatpak on FlatHub .....

My concern is about the viruses & spy-ware. You know that WineHQ can run viruses & spy-ware on Linux & this is very bad thing ..... From power points of flatpak is the fact that it is sandbox ...... However, sandbox can be adopted by packager (& user), weakened or strengthened. I would like to know about if you taking this point or not:
1) Is this flatpak PRE-CONFIGURED against risk of run a virus/spy-ware so that damage will be to lest possible level or not ? 
2) if a virus run by WineHQ through this flatpak, then does it will behave as if it run within a virtual machine ?
3) does the fact that the current flatpak downloading WineHQ directly from repository (WineHQ not packaged as flatpak run time or base application) will make it less secure from case if WineHQ were packaged as flatpak (run time or base application) ?

Finally, I would like to explain how I will install this flatpak on my system:
1) I'm already created a special user account without su/sudo/polkit power (no any root power at all),
2) install flatpak package from terminal of this special rootless account using "--user" flag as following:
`$ flatpak install flathub com.usebottles.bottles --user`
Is this enough or there is further step(s) ?

I was waiting Q4Wine but your application came & it seem that it is better & of more options with more active development ....

**Comment by mirkobrombin** [comment]
Hi! I admit that I have not yet gone through with the Flatpak. At this time Bottles only has write access only to one directory:
https://github.com/flathub/com.usebottles.bottles/blob/3bd772c1186dda669f2b2a1eabe3e95393f49d6a/com.usebottles.bottles.yml#L22

Unfortunately, it is not possible for me (for now) to guarantee total isolation as even if Bottles has restricted permissions, the installed programs can be run from outside Bottles.

**Comment by Nokia808** [comment]
@mirkobrombin 
You said "even if Bottles has restricted permissions, the installed programs can be run from outside Bottles." ! How this ? Is this due to the fact that WineHQ is currently not packaged as flatpak (run time, or base application) ?

**Comment by mirkobrombin** [comment]
> @mirkobrombin
> You said "even if Bottles has restricted permissions, the installed programs can be run from outside Bottles." ! How this ? Is this due to the fact that WineHQ is currently not packaged as flatpak (run time, or base application) ?

No is given by the fact that you can also run installed programs from the e.g. GNOME applications menu for example. WineHQ (the runners) are downloaded from GitHub from the Lutris repository and that's not the problem but the software you install (like Notepad ++, Steam, ..).

**Comment by Nokia808** [comment]
@mirkobrombin 
And what happened if run installed program from GNOME application menu ? Yes, it could be initiated from outside your application, but after initiation it should run within restricted limits of your flatpak, isn't it ??

**Comment by Nokia808** [comment]
@mirkobrombin 
Does downloaded WineHQ from Lutris repository will involved by sandbox of your flatpak or not ? If yes, then even if installed program run from GNOME applications menu, it should be still sandbox .....

**Comment by mirkobrombin** [comment]
> @mirkobrombin
> And what happened if run installed program from GNOME application menu ? Yes, it could be initiated from outside your application, but after initiation it should run within restricted limits of your flatpak, isn't it ??

No in that case these are started outside the flatpak and use the user's permissions. With the Bottles redesign process (https://github.com/bottlesdevs/Bottles/issues/77) we want to warn the user of the risk of running Windows binaries, regardless of whether these are reliable or not. However as long as you run applications from inside Bottles, they should be limited by Flatpak permissions.

**Comment by mirkobrombin** [comment]
> @mirkobrombin
> Does downloaded WineHQ from Lutris repository will involved by sandbox of your flatpak or not ? If yes, then even if installed program run from GNOME applications menu, it should be still sandbox .....

No because when you start application from the applications menu of your Desktop Environment of choose, applications don't run through Bottles.

**Comment by Nokia808** [comment]
@mirkobrombin 
As I expected exactly ! The cause of this behaviour is that the WineHQ that used is not sandbox because it is NOT A FLATPAK ! This is the same problem of Phoenicis !

Can your flatpak utilize Lutris runner which is already packaged as a flatpak ? It is available at the following link:
https://github.com/flathub/net.lutris.Lutris.Runner.Wine

As you see, Lutris flatpak has it's WineHQ already packaged as flatpak so every installed Windows program should be involved by sandbox by default .......

**Comment by AsciiWolf** [comment]
@Nokia808 You don't need Wine runners to be packaged as Flatpak extensions to be able to run them inside Flatpak. Take a look at how this is handled in Steam Proton (the older builds that do not require Pressure Vessel), for example.

**Comment by Nokia808** [comment]
@AsciiWolf 
So, how windows programs can be run from behind bottles flatpak ?? I'm not programmer &  can not understand the code, but it seem to me that there are 2 reasons for that:
1) either design (due to aims) of bottles requiring this. In this case, it will be a great loss ......
2) or the packager of flatpak version of bottles (his developer) currently not experienced with how to prevent this on flatpak, due to being new for flatpak packaging. In this case, it is easy & we can wait him.
But I feel that possibility number (1) is the cause - hope I'm wrong.

**Comment by LeandroStanger** [comment]
Add support for [Unchecky: unchecky.com](https://unchecky.com)

**Comment by AsciiWolf** [comment]
@LeandroStanger This is offtopic here and would possibly be really hard to implement in Bottles/Wine.
