### ISSUE TITLE
Reduce filesystem permissions 

### ISSUE THREAD

**Issue by jannuary** [flathub/com.usebottles.bottles#120]
Currently, Bottles has a whopping 12 different filesystem permissions. Now that we use portals, it wouldn't hurt to go through different permission and reduce ones that aren't needed.

**Comment by mirkobrombin** [comment]
> Currently, Bottles has a whopping 12 different filesystem permissions. Now that we use portals, it wouldn't hurt to go through different permission and reduce ones that aren't needed.

Good idea! This should be scheduled for 2021.8.14. Can you please open an issue in the main repository so I can track it in the project?

**Comment by BrainBlasted** [comment]
Since the filesystem permissions have been reduced, it is not possible for Bottles to load dlls or other dependencies in the same when using the "Run Executable" button. I think it makes sense UX wise to leave the filesystem permissions in for now, otherwise Bottles is less useful without configuration.

**Comment by mirkobrombin** [comment]
DLL are in the bottle path not outside. If you program is not working, maybe there is another problem.

**Comment by BrainBlasted** [comment]
That is not the case for DLLs included with a program. Say I have `DoSomething.exe` and it requires `special_do_things.dll`. This DLL is included in the same folder as the exe. When opening via the file chooser via the "Run Executable" button, which I assume uses GtkFileChooserNative, Bottles is only given access to the individual file handed to it by the portal. It is not given access to the directory, thus things in the sandbox cannot access related files in the same folder. If you give Bottles filesystem permissions (e.g. `--filesystem=home`) it can access said files without issue.

**Comment by mirkobrombin** [comment]
> That is not the case for DLLs included with a program. Say I have `DoSomething.exe` and it requires `special_do_things.dll`. This DLL is included in the same folder as the exe. When opening via the file chooser via the "Run Executable" button, which I assume uses GtkFileChooserNative, Bottles is only given access to the individual file handed to it by the portal. It is not given access to the directory, thus things in the sandbox cannot access related files in the same folder. If you give Bottles filesystem permissions (e.g. `--filesystem=home`) it can access said files without issue.

Ah. Can you move this discussion here: https://github.com/bottlesdevs/Bottles/issues/413 ?

So I can tag other developers.
