### ISSUE TITLE
[Question] How can I run a Windows program from CLI with Bottles Flatpak?

### ISSUE THREAD

**Issue by felipehw** [flathub/com.usebottles.bottles#14]
Hi, I'm new to Bottles.

How can I run a Windows program from CLI with Bottles Flatpak?

I tried (without success):
- `flatpak run --command=wine com.usebottles.bottles test.exe`
- `flatpak run --command=bottles com.usebottles.bottles test.exe`
- `flatpak run com.usebottles.bottles test.exe`

**Comment by felipehw** [comment]
The developer answered: <https://github.com/bottlesdevs/Bottles/discussions/137#discussioncomment-412550>

**Comment by tgschultz** [comment]
The link is defunct and therefore useless.

**Comment by felipehw** [comment]
See here: https://docs.usebottles.com/bottles/run-.exe-.msi-.bat-.lnk-files
E.g.:
Without Flatpak
```
bottles -b bottle_name -e /full/executable/path
```
With Flatpak:
> Note: use `flatpak run com.usebottles.bottles` instead of `bottles` for flatpak.

**Comment by tgschultz** [comment]
The instructions do not work. The command appears to launch and immediately exit.
