### ISSUE TITLE
Wine Executables doesn't work in GNOME wayland session

### ISSUE THREAD

**Issue by jjardon** [flathub/com.usebottles.bottles#141]
Bottles version: 2021.8.28-treviso-1

This is the error:
```
Aug 29 05:22:20 rhun com.usebottles.bottles.desktop[219711]: 0040:err:setupapi:SetupDefaultQueueCallbackW copy error 1812 L"@C:\\windows\\system32\\drivers\\wineusb.sys,-1" -> L"C:\\windows\\inf\\w>
Aug 29 05:22:20 rhun com.usebottles.bottles.desktop[219721]: 0060:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
Aug 29 05:22:20 rhun com.usebottles.bottles.desktop[219721]: 0060:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
Aug 29 05:22:21 rhun com.usebottles.bottles.desktop[219737]: 0090:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
Aug 29 05:22:21 rhun com.usebottles.bottles.desktop[219737]: 0090:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
```

I've restarted GNOME in Xorg session and everything is ok

**Comment by jjardon** [comment]
This seems same issue as https://github.com/bottlesdevs/Bottles/issues/419

**Comment by mirkobrombin** [comment]
It's definitely the same problem, I re-open the other issue and we'll track it there

**Comment by Eoin-ONeill-Yokai** [comment]
I'm still having this issue on KDE wayland.

**Comment by srevinsaju** [comment]
By using [flatseal](https://flathub.org/apps/details/com.github.tchx84.Flatseal), I removed the "socket=fallback-x11" permission from Bottles and it started working again on KDE Wayland

![image](https://user-images.githubusercontent.com/48695438/142978456-e8bbf799-c7dc-4cf3-a3bc-45c5fa3da7de.png)

**Comment by lestephane** [comment]
I'm still experiencing this, and https://github.com/bottlesdevs/Bottles/issues/419 was closed with not much of a comment.
I've tried @srevinsaju suggestion, to no avail. What is the 2023 way to run Bottles on wayland?

```
01d4:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
01d4:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
```
