### ISSUE TITLE
`devel` permission enabled by default?

### ISSUE THREAD

**Issue by kparal** [flathub/com.usebottles.bottles#293]
Hello, ed43df831a87 enabled a new `devel` permission. I found a [documentation](https://docs.flatpak.org/en/latest/flatpak-builder-command-reference.html) which says:
> Builds have the --allow=devel and --allow=multiarch permissions that regular flatpak runs don't have by default. This limits the syscall filtering that is normally done so development tools like debuggers work. Otherwise the build sandbox is very limited, for example there is no network access. 

I wonder why the `devel` permission is needed? It sounds like an unnecessary hole into the sandbox. If somebody wants to debug the Bottles flatpak, they can always use Flatseal or `flatpak override` and add the `debug` permission locally. So why is this enabled by default? Thanks for explanation.

**Comment by mirkobrombin** [comment]
Hi,  please read this conversation https://github.com/bottlesdevs/documentation/issues/12

**Comment by kparal** [comment]
Thanks! That has been very informative. It seems enabling the `devel` permission is the best solution at the moment (and the fact that Steam flatpak also uses it grants some confidence). Closing this ticket. (Btw, if you mention a related ticket in a git commit message next time, people won't bother you with questions as much :smile: )

**Comment by mirkobrombin** [comment]
I usually do (when I remember) 😅
