### ISSUE TITLE
Question: is this an appropriate place for filing bugs on incorrect Windows program behavior?

### ISSUE THREAD

**Issue by DuckDuckWhale** [flathub/com.usebottles.bottles#397]
I'm trying to run a particular application inside Bottles Flatpak (beta) and the textbox doesn't take input.

**Comment by nonetrix** [comment]
I would go to the [Wine issue tracker](https://bugs.winehq.org/) or [Bottles issue tracker](https://github.com/bottlesdevs/Bottles/issues/new/choose) rather than the Flatpak package which likely isn't the issue

**Comment by TheEvilSkeleton** [comment]
I'm closing this issue, as it was reported last year. As nonetrix said, if you run into issues, please open it in the Bottles issue tracker.
