### ISSUE TITLE
[Feature request] Prevent installed Windows applications from being run from behind this flatpak

### ISSUE THREAD

**Issue by Nokia808** [flathub/com.usebottles.bottles#4]
Hi. 

This request on behalf of the following discussion: https://github.com/flathub/com.usebottles.bottles/issues/1

It is a request for future work & development of this flatpak. If not opposite to the design & aims of Bottles, then all installed Windows applications should by default prevented from being run from behind Bottles, at lest Bottles flatpak package.

Take your time to implement this feature, but kindly give it a priority because without this feature, without preventing windows programs from being run outside this flatpak, the flatpak package loss too much of it's credits ....

Best.

**Comment by mirkobrombin** [comment]
Thank you for taking the time to report this feature.However, I believe that if for some it may be useful, for others the lack of integration with the application menu can be a missing feature.

An optional, user-activated setting may make sense.I won't prioritize this feature for now as we already have more in the queue but I don't want to say I won't work on it.

**Comment by AsciiWolf** [comment]
Wouldn't be possible to have something like `flatpak run com.usebottles.bottles --command=...` on an Exec line of the created desktop files instead of running the Wine apps directly, without Flatpak?

**Comment by Nokia808** [comment]
@AsciiWolf 
I see this a very good idea ! Just small modification by developer for flatpak version from original version & we will set an end for nightmares of viruses ......

**Comment by mirkobrombin** [comment]
The Flatpak version is the original version. There are no extra modifications and I don't like the idea of ​​providing variations.

As mentioned in some issues in the official repository, I have no control over what wine does once a program is installed.If you notice there is an "Installers" tab, this will allow you to install programs controlled by Bottle, once the program is installed, you can choose whether or not to add the icon to the program list of your desktop env.This feature is currently not actively developed, we will resume development of the feature once v3 is deployed.

**Comment by Nokia808** [comment]
@mirkobrombin 
Dear does you mean that ALL risks came from icons that added to the program list of desktop env. ? In this case, can the manual removal of these icons provide complete protection & removal of all risks till the time you find more elegant suitable solution ??

**Comment by mirkobrombin** [comment]
If you run programs from bottles you should have no risks (or limited)

**Comment by AsciiWolf** [comment]
So, Wine applications launched directly from Bottles are being run inside the Flatpak sandbox? That's good! In that case, please consider removing the desktop files creation functionality. It would be the easiest solution to this security problem. The only downside of this is that all applications would need to be launched from Bottles.

**Comment by AsciiWolf** [comment]
So, Wine applications launched directly from Bottles are being run inside the Flatpak sandbox? That's good! In that case, please consider removing the desktop files creation functionality. It would be the easiest solution to this security problem. The only downside of this is that all applications will need to be launched from Bottles.

**Comment by AsciiWolf** [comment]
So, Wine applications launched directly from Bottles are being run inside the Flatpak sandbox? That's good! In that case, please consider removing the desktop files creation functionality. It would be the easiest solution to this security problem. The only downside of this is that all applications would need to be launched from Bottles.

**Comment by AsciiWolf** [comment]
@nedrichards @bilelmoussaoui What is your opinion about this? Is it ok when Flatpak application breaks sandbox this way?

**Comment by mirkobrombin** [comment]
As I think I've already said in a handful of issues: I have no control over the desktop files created by Wine. Also this may be a lack of functionality for others.

**Comment by mirkobrombin** [comment]
I keep the issue open as a reminder after Bottles v4 release

**Comment by mirkobrombin** [comment]
Thanks to libwine and libbottles we will have more control over what Wine does in the system. This issue will be resolved with Bottles v4 (sooner or later).
