### ISSUE TITLE
Bitdefender flagging winhlp32 as a Threat

### ISSUE THREAD

**Issue by kristianwh** [flathub/com.usebottles.bottles#404]
I got a message from my sysadmin that this software had a threat in it:
![image](https://user-images.githubusercontent.com/2349815/183877567-c04c2f90-9559-4bcc-9578-9d5522227028.png)
Is this real, or just a false positive?

**Comment by mirkobrombin** [comment]
False positive, that file is part of wine and built with wine (actually WineHQ on Flathub). Wine try to convert/emulate (not an emulator) windows calls to posix compatible calls. So, some files may be reported because of this.

**Comment by kristianwh** [comment]
Thanks, closing this then :)
