### ISSUE TITLE
Different behavior using Programs menu vs Run Executable button

### ISSUE THREAD

**Issue by mcross829** [flathub/com.usebottles.bottles#409]
It seems DLL overrides are not working when a program is launched from the Programs menu, but when launching the same .exe from the same location using the Run Executable button, the DLL overrides work as intended. It seems to apply for every program I've tried to run, and it seems to apply to all wine runners.

If it helps, I'm trying to run older games that use a DLL for an ASI loader (_SilentPatch for GTA or ThirteenAG's widescreen patches_). These usually use dinput8.dll, and these patches only work when the game is ran from the Run Executable button.
<br>

Sorry if this is expected behavior but I can't seem to find anything online about this, and I haven't completely wrapped my head around how bottles works with its sandbox behavior, but I do suspect I'm encountering some issue with the working directory.

**Comment by mirkobrombin** [comment]
Fixed in current branch. Also please use the Bottles repository for bug reporting 😁
