### ISSUE TITLE
Can't Launch Programs on RHEL 9

### ISSUE THREAD

**Issue by tkuraku** [flathub/com.usebottles.bottles#415]
I am trying to launch battle.net that I installed from the launcher options in my gaming bottle. Nothing happens when I try to run the program. Everything worked perfectly on RHEL 8. Not sure what the issue is.

**Comment by TheEvilSkeleton** [comment]
Sorry for the late response, but can you open an issue in the [Bottles issue tracker](https://github.com/bottlesdevs/Bottles/issues) and fill the form? I'm closing this issue.
