### ISSUE TITLE
Add default xdg-data/applications permission

### ISSUE THREAD

**Issue by freechelmi** [flathub/com.usebottles.bottles#463]
I know this is always a difficult choice to add a permission to a flatpak

But currently it's impossible to recommend Bottles to casual linux users although they are a wide share of the targeted public for Bottles.

Because that even after a user has sucessfully installed a software in a bottle , he cannot find the software in his linux "desktop files" ( eg : list of applications ) 

Also I think the flatpak bottles should have the xdg-data/applications r/w access permission in order for normal users to be able to create desktop entries 

This is also necessary to be able to implement this issue for automatic desktop file creation 
https://github.com/bottlesdevs/Bottles/issues/3181

**Comment by orowith2os** [comment]
We can just use the appropriate portal for this instead.
