### ISSUE TITLE
Change log on "www.flathub.org" is still for version 2.0.9 though application now is version 2.1.0.7

### ISSUE THREAD

**Issue by Nokia808** [flathub/com.usebottles.bottles#6]
Hi.

Just see this:
https://www.flathub.org/apps/details/com.usebottles.bottles

The change log on the above page point to version 2.0.9 ! Moreover, it started by "Happy new year", while Valentin day had already passed before 4 days ago ! Is this intended ? I think this is not appropriate & should be updated.

**Comment by mirkobrombin** [comment]
> Check bottles version from the about dialog. Idk why flathub is showing the wrong version even if it is actually installing the latest.

**Comment by mirkobrombin** [comment]
Fixed

**Comment by Lvaskz** [comment]
Some regression here?
<img width="767" alt="Screenshot_2021-02-26 Bottles—Linux Apps on Flathub" src="https://user-images.githubusercontent.com/29207169/109336951-b922f400-7829-11eb-97a8-73125fa8b744.png">
