### ISSUE TITLE
Missing --filesystem=xdg-run/gvfsd privilege?

### ISSUE THREAD

**Issue by guihkx** [flathub/com.usebottles.bottles#61]
Whenever I click the "Run .exe" button, the following message gets spammed in the terminal:

```
(bottles:2): GVFS-WARNING **: 18:03:32.053: The peer-to-peer connection failed: 
Error while getting peer-to-peer dbus connection: 
Could not connect: No such file or directory. Falling back to the session bus.
Your application is probably missing --filesystem=xdg-run/gvfsd privileges.
```

And sure, manually adding `--filesystem=xdg-run/gvfsd` does make the message go away...

```bash
$ flatpak override --user --filesystem=xdg-run/gvfsd com.usebottles.bottles
```

So I think this permission should be added to the manifest. Thoughts?

OS: Arch Linux
Desktop Environment: GNOME 40

**Comment by guihkx** [comment]
Actually, although that warning went away, now a new warning is displayed after the file chooser opens:

```
(bottles:2): Gtk-WARNING **: 18:08:12.114: Failed to measure available space: 
Error getting filesystem info for /mnt/HDDLinux: No such file or directory
```

FWIW, `/mnt/HDDLinux` is the directory where my hard disk is mounted to. I cannot access the path using the file chooser.

**Comment by tim77** [comment]
https://github.com/flathub/flathub/issues/2180

**Comment by guihkx** [comment]
Hmm, so if I understand correctly, Bottles doesn't actually need this permission?

Alright then, closing. Thank you! :)
