### ISSUE TITLE
Not Enough Disk Space even if I have

### ISSUE THREAD

**Issue by TheEvilSkeleton** [flathub/com.usebottles.bottles#74]
Hi,

I'm trying to install a game that is over 4GB but Bottles is preventing me to do so apparently. I have a lot more than 45GB for the record:

![image](https://user-images.githubusercontent.com/50847364/117701749-9bf99280-b195-11eb-98e8-d63d3f3546d0.png)

FYI I have `~/.local/share/bottles` symlinked to my HDD, which has 645GB free. Before, I tried on my SSD, which has more than 45GB free as well, but the exact same issue popped up.

**Comment by mirkobrombin** [comment]
This looks more like a wine mistake than Bottles. Try using the AppImage to see if it's flatpak specific.

**Comment by tim77** [comment]
I'd try to add permission for this HDD via Flatseal/CLI first and then add this HDD as virtual disk in Wine. Looks like currently 4GB is a limitation of your virtual FS in tmpfs.

**Comment by mirkobrombin** [comment]
> I'd try to add permission for this HDD via Flatseal/CLI first and then add this HDD as virtual disk in Wine. Looks like currently 4GB is a limitation of your virtual FS in tmpfs.

Do you know if these limits can be increased and if it is safe to do so?

**Comment by TheEvilSkeleton** [comment]
> I'd try to add permission for this HDD via Flatseal/CLI first

Since Bottles allows rw to `/run/media`, my HDD is automatically found and used.

> and then add this HDD as virtual disk in Wine. Looks like currently 4GB is a limitation of your virtual FS in tmpfs.

Can you guide me through it? I don't know how to do that.

**Comment by tim77** [comment]
> Do you know if these limits can be increased and if it is safe to do so?

Defaults based on overall amount of physical RAM. It's possible to change them, but IMO we should found proper solution for this.

> Can you guide me through it? I don't know how to do that.

Run `winecfg` or run Wine configuration via Bottles itself. And there is such menu for drives configuration:
![Screenshot_20210511_143548](https://user-images.githubusercontent.com/5614476/117809215-95871b80-b266-11eb-8a0f-c58a1ec1a7cb.png)

**Comment by mirkobrombin** [comment]
> > Do you know if these limits can be increased and if it is safe to do so?
> 
> Defaults based on overall amount of physical RAM. It's possible to change them, but IMO we should found proper solution for this.
> 
> > Can you guide me through it? I don't know how to do that.
> 
> Run `winecfg` or run Wine configuration via Bottles itself. And there is such menu for drives configuration:
> ![Screenshot_20210511_143548](https://user-images.githubusercontent.com/5614476/117809215-95871b80-b266-11eb-8a0f-c58a1ec1a7cb.png)

This should also be implemented in libwine
Ref: https://github.com/bottlesdevs/libwine/issues/2

**Comment by mirkobrombin** [comment]
Ping https://github.com/bottlesdevs/LibraryWine/issues/1
