### ISSUE TITLE
What happened?

### ISSUE THREAD

**Issue by nickavem** [flathub/com.usebottles.bottles#90]
Why is bottles leaving Flathub? Are they planning to host their own flatpak repo, or leave flatpak altogether? I was really excited about a GTK, flatpak, wine solution, and am curious about this decision.

**Comment by mirkobrombin** [comment]
Read more: https://mirko.pm/blog/bottles-will-leave-flatpak/

**Comment by tim77** [comment]
@mirkobrombin thanks for your work. Sad to hear TBH. Wine+Flatpak is great combo. I would sat must have for Wine since most of the time users running untrusted code in Wine and Flatpak with proper isolation there is a first and last bastion.

**Comment by nickavem** [comment]
> Read more: https://mirko.pm/blog/bottles-will-leave-flatpak/
> Bottles will no longer ship as Flatpak for now but remain actively developed and distributed as Appimage, deb, AUR, rpm and snap

That is disappointing, but understandable.

**Comment by mirkobrombin** [comment]
Unfortunately I don't have the skills to maintain the Bottles flatpak as well but someone else can. I will be happy if someone decides to take care about the Flatpak version of Bottles and I would gladly collaborate with this if it does not take me too long.

Open source is a beautiful and vast world, there are many people ready to help thanks to this model of openness. So I'm confident that sooner or later, someone with the right skills will bring Bottles back to Flathub.

**Comment by jurf** [comment]
I’ve read the blog post and respect your decision, but I don’t understand the point with the reviews. How did you manage to filter reviews by the installation method? Also, while I know that negative reviews do not feel nice, but people complaining about Wine problems feels more like a problem with app communication than the platform.

**Comment by mirkobrombin** [comment]
> I’ve read the blog post and respect your decision, but I don’t understand the point with the reviews. How did you manage to filter reviews by the installation method? Also, while I know that negative reviews do not feel nice, but people complaining about Wine problems feels more like a problem with app communication than the platform.

Well I'm not a man of advertising and big words but it shouldn't be too complex to understand that Bottles is not Wine 🤔. Either way, this is a hobby for me and I don't really have the time to think about how to explain such a simple concept. 

I don't think I've ever written that I want to "filter reviews", and I hope it is clear that the decision to leave is exclusively related to my lack of time and knowledge.

**Comment by jurf** [comment]
> I don't think I've ever written that I want to "filter reviews", and I hope it is clear that the decision to leave is exclusively related to my lack of time and knowledge.

Sorry, I should’ve explained myself better. You mention you browsed reviews on GNOME Software – the source of my confusion was that you attributed them to Flatpak users, which lead me to believe you found a way to filter the reviews by installation method, of which I am not aware.

Unless you use different app IDs (in the AppData) for different packages, they will have the same ID in ODRS. Since GNOME Software queries the ODRS by the ID of the installed package, it will receive reviews submitted from any installation method.

**Comment by mirkobrombin** [comment]
> > I don't think I've ever written that I want to "filter reviews", and I hope it is clear that the decision to leave is exclusively related to my lack of time and knowledge.
> 
> Sorry, I should’ve explained myself better. You mention you browsed reviews on GNOME Software – the source of my confusion was that you attributed them to Flatpak users, which lead me to believe you found a way to filter the reviews by installation method, of which I am not aware.
> 
> Unless you use different app IDs (in the AppData) for different packages, they will have the same ID in ODRS. Since GNOME Software queries the ODRS by the ID of the installed package, it will receive reviews submitted from any installation method.

Ok I understood more, my fault. No, I haven't found a way to filter, Flatpak is the only Bottles package supported by GNOME Software. In the sense, ok that the IDs are common and currently our RDNN is com.usebottles.bottles but we don't have any other GNOME Software compatible packages.

I could be wrong but none of the following should be compatible with GNOME Software and therefore shouldn't have reviews on that store:
- AUR (not a Pacman repo)
- Snap (actually the Snapcraft store is based on GNOME Software but behaves differently)
- AppImage
- NixOS

Unless it has been distributed to other repositories, they should all come from Flatpak (maybe am I wrong?).

**Comment by jurf** [comment]
It’s not about GNOME Software but rather ODRS, the review system it uses.

The Snap Store uses the ODRS too. GNOME Software uses PackageKit, which in turn supports Debian, Fedora and openSUSE packages, so there’ll be reviews from those also. Provided, of course, that you package the Appstream file with them.

**Comment by mirkobrombin** [comment]
> It’s not about GNOME Software but rather ODRS, the review system it uses.
> 
> The Snap Store uses the ODRS too. GNOME Software uses PackageKit, which in turn supports Debian, Fedora and openSUSE packages, so there’ll be reviews from those also. Provided, of course, that you package the Appstream file with them.

I can confirm that the Appatream file was not included in snapcraft.

**Comment by mirkobrombin** [comment]
> https://github.com/bottlesdevs/Bottles#unofficial-packages
> 
> lists com.usebottles.bottles as an "Unofficial packages"
> perhaps that should be deleted?

The beta is still available on Flathub beta but not officially supported

**Comment by Yajo** [comment]
Regarding some of the issues you mention in the blog post, and with zero intentions on invalidating anybody's opinions (everyone has one), I can share some suggestions with you:

- If you want good bug reports, [set up good templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-templates).
- Set up some well thought [saved replies](https://docs.github.com/en/github/writing-on-github/working-with-saved-replies) to quickly close any issue that:
  - doesn't follow the template
  - is not in English
  - is a Wine issue
  - doesn't provide enough STR
- If you don't want non-English logs, then remove translations on the log emitter parts. Translations should only exist in UI parts of any program.

These things worked for me and made my life easier. And for you, they should improve your experience, no matter the reporter install method.

The life of the hobby FLOSS maintainer is not easy! 😃

**Comment by mirkobrombin** [comment]
> Regarding some of the issues you mention in the blog post, and with zero intentions on invalidating anybody's opinions (everyone has one), I can share some suggestions with you:
> 
> * If you want good bug reports, [set up good templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-templates).
> * Set up some well thought [saved replies](https://docs.github.com/en/github/writing-on-github/working-with-saved-replies) to quickly close any issue that:
>   
>   * doesn't follow the template
>   * is not in English
>   * is a Wine issue
>   * doesn't provide enough STR
> * If you don't want non-English logs, then remove translations on the log emitter parts. Translations should only exist in UI parts of any program.
> 
> These things worked for me and made my life easier. And for you, they should improve your experience, no matter the reporter install method.
> 
> The life of the hobby FLOSS maintainer is not easy!

So we have (good?) issue templates: https://github.com/bottlesdevs/Bottles/tree/master/.github/ISSUE_TEMPLATE
Regarding the translated logs it was mostly to entice the user to read and understand them but actually this could be a problem .. 🤔

Thank you very much for your advice, I will try to follow them! 🙏

**Comment by dsd** [comment]
Thanks @mirkobrombin for your hard work on bringing Bottles to flathub and maintaining it up until now! It's been great to be able to point Endless OS users to a user-friendly, potential solution that might let their Windows apps run, when such requirements emerge.

I also have the feeling that the friction and frustration you have encountered in reviews and other communication from the flathub user community is probably (hopefully?) more of a result of the high popularity of Flathub as a method to obtain and use Bottles (or in other words, Bottles' success in plugging a need amongst the community of users who routinely get their apps from Flathub), plus the ease of being able to file issues and leave reviews on this platform, rather than an inherent flaw in the Flathub community.

I completely understand the technical challenges & time implications around maintainership though. I am curious from your interactions with the community if you have any suggestions of good candidates who may be interested in continuing maintenance of Bottles on flathub?

**Comment by mirkobrombin** [comment]
> Thanks @mirkobrombin for your hard work on bringing Bottles to flathub and maintaining it up until now! It's been great to be able to point Endless OS users to a user-friendly, potential solution that might let their Windows apps run, when such requirements emerge.
> 
> I also have the feeling that the friction and frustration you have encountered in reviews and other communication from the flathub user community is probably (hopefully?) more of a result of the high popularity of Flathub as a method to obtain and use Bottles (or in other words, Bottles' success in plugging a need amongst the community of users who routinely get their apps from Flathub), plus the ease of being able to file issues and leave reviews on this platform, rather than an inherent flaw in the Flathub community.
> 
> I completely understand the technical challenges & time implications around maintainership though. I am curious from your interactions with the community if you have any suggestions of good candidates who may be interested in continuing maintenance of Bottles on flathub?

Hello! Unfortunately I haven't found a maintainer yet. I'm sorry not to offer Bottles as flatpak because I want to reach as many users as possible, but unfortunately I can't take care of that too.

I noticed a lot of disappointment in my choice to abandon Flatpak and although I explained my reasons, I can also understand the disappointment of these users. I've been thinking about putting Bottles back on Flathub for days.

**Comment by dsd** [comment]
I think that would be welcomed by many! And its easier said than done to create some distance, but you could consider a very light touch Flathub maintenance approach where you just bump the manifest from time to time and only pay attention to issues that come with patches attached. Of course such maintenance style is not ideal, but it's better than not having it available on Flathub at all, in my opinion (for time reasons, my own flatpaks are maintained like this). If the manifest gets behind (e.g. new version becomes available) you might even get some first stage contributors sending in simple pull requests.

**Comment by mirkobrombin** [comment]
> I think that would be welcomed by many! And its easier said than done to create some distance, but you could consider a very light touch Flathub maintenance approach where you just bump the manifest from time to time and only pay attention to issues that come with patches attached. Of course such maintenance style is not ideal, but it's better than not having it available on Flathub at all, in my opinion (for time reasons, my own flatpaks are maintained like this). If the manifest gets behind (e.g. new version becomes available) you might even get some first stage contributors sending in simple pull requests.

I like the idea, I could keep the flatpak stable version a version back, so I can fix any bugs in the Flatpak beta and put everything in stable when it actually is.To date, the beta version has not been very successful as no one has used it to test the new features.Anyway I think about it, analyzing the pros and cons, thank you very much for the idea, much appreciated.

**Comment by Yajo** [comment]
Another option you have, that should make maintenance easier, is to use the appimage as a source for the flatpak, instead of building it separately. That way, you reduce the possibilities of bugs being reproducible in the flatpak but not in the AppImage.

For example, [that's what Jitsi Meet flatpak does](https://github.com/flathub/org.jitsi.jitsi-meet/blob/6e36e62a9017c3e81f3c8a7cc26543823e7ca326/org.jitsi.jitsi-meet.yaml#L81-L83). And upgrading to a new release is as easy as https://github.com/flathub/org.jitsi.jitsi-meet/commit/a6ff7c400b970de6d2d9f34265cc899d18ebefa8.

Doing that, in practical terms you're just using the same build. The only chances of something happening in flatpak but not outside of it would be due to its sandboxing capabilities. In this case, it could reveal a problem in the sandbox configuration, or a problem in the app, that would be trying to do something it shouldn't.

**Comment by mirkobrombin** [comment]
> Another option you have, that should make maintenance easier, is to use the appimage as a source for the flatpak, instead of building it separately. That way, you reduce the possibilities of bugs being reproducible in the flatpak but not in the AppImage.
> 
> For example, [that's what Jitsi Meet flatpak does](https://github.com/flathub/org.jitsi.jitsi-meet/blob/6e36e62a9017c3e81f3c8a7cc26543823e7ca326/org.jitsi.jitsi-meet.yaml#L81-L83). And upgrading to a new release is as easy as [flathub/org.jitsi.jitsi-meet@a6ff7c4](https://github.com/flathub/org.jitsi.jitsi-meet/commit/a6ff7c400b970de6d2d9f34265cc899d18ebefa8).
> 
> Doing that, in practical terms you're just using the same build. The only chances of something happening in flatpak but not outside of it would be due to its sandboxing capabilities. In this case, it could reveal a problem in the sandbox configuration, or a problem in the app, that would be trying to do something it shouldn't.

That is also a good idea, but at the moment the problems encountered are precisely regarding the sandbox and in general problems of permissions in the use of commands and processes.

I'm taking some time to read up on it, for example how to spawn a new terminal (eg gnome-terminal) from the flatpak, which cannot be done at the moment.

**Comment by mirkobrombin** [comment]
I would like to "close" this issue with some updates and information.

For a few hours I have sent a new build to Flathub (2017.7.1-treviso), it is the last stable build from the mainline. This means Bottles is back on Flathub but there will be some differences.

There are currently 2 versions of the flatpak:
- stable (branch master)
- beta

In the case of stable, it will not follow the normal release cycle like all other packages but will see a total of 2 monthly updates, with a proposed frequency on the 14th and 28th of each month. In this update phase, the Flatpak will be aligned to the latest stable release from the mainline (this is not necessarily the latest build).

This is not a choice to "make Flathub users suffer" but of model proposals that will then be propagated in the future to all other official packages.

Regarding the version, we switched to a CalVer model for several reasons but I refer you to the issue on the official repository for more information: https://github.com/bottlesdevs/Bottles/issues/339

I want to thank all users and developers for their advice and for making me change my choice.

**Comment by sonnyp** [comment]
> Unfortunately I don't have the skills to maintain the Bottles flatpak as well but someone else can. I will be happy if someone decides to take care about the Flatpak version of Bottles and I would gladly collaborate with this if it does not take me too long.

@mirkobrombin feel free to mention or assign me any time for questions or reviews, happy to help

**Comment by mirkobrombin** [comment]
> > Unfortunately I don't have the skills to maintain the Bottles flatpak as well but someone else can. I will be happy if someone decides to take care about the Flatpak version of Bottles and I would gladly collaborate with this if it does not take me too long.
> 
> @mirkobrombin feel free to mention or assign me any time for questions or reviews, happy to help

You make me blush :D Is it ok for you to join the org?

**Comment by sonnyp** [comment]
Happy to - can't make promises about the time I dedicate to Bottles though but happy to help when/where I can.

**Comment by IverCoder** [comment]
Years later and Bottles is now Flatpak-only... (at least, in an official sense)
